name: Shintemenu
main: eric.me.shintemenu.Main
version: 1.0
author: EricSiu
api-version: 1.13
commands:
  shinte:
    description: Opens the server menu.
    aliases: [menu, servermenu, akatsukisora]
    permission: menu.shinte
    permission-message: You do not have permission menu.shinte
permissions:
  menu.shinte:
    description: Allows you to use /akatsukisora.
    default: true